slam_toolbox:
  ros__parameters:
    use_sim_time: false  # Zet dit op true als je een simulatie gebruikt
    map_file_name: ""  # Laat dit leeg als je een nieuwe kaart wilt maken
    mode: "mapping"  # Gebruik "mapping" voor het maken van een kaart
    resolution: 0.05  # Resolutie van de kaart, in meters
    publish_map: true  # Publiceer de kaart tijdens het maken
    map_update_interval: 5.0  # Interval in seconden voor het bijwerken van de kaart
    laser_scan_topic: "/scan"  # Het topic van jouw lidar
    use_scan_matching: true  # Gebruik scan matching voor betere kaartresultaten
    use_slam_backend: true  # Gebruik de SLAM-backend voor optimalisatie
    max_laser_range: 12.0  # Maximale afstand die de lidar kan meten
    minimum_travel_distance: 0.1  # Minimale afstand die de robot moet afleggen om de kaart bij te werken
    minimum_travel_angle: 0.1  # Minimale hoekverandering voor kaartbijwerking
    queue_size: 100

